<?php

/**
 * Implements hook_user_login().
 */
function civicrm_user_connected_orgs_user_login($edit, $account) {
  civicrm_initialize();

  try {
    // Populate contact details.
    $_SESSION['civicrm_user_connected_orgs'] = civicrm_api3('UFMatch', 'getsingle', array(
      'sequential' => 1,
      'uf_id' => $account->uid,
    ));
    // Populate active memberships.
    // 1. First get the list of active membership types.
    $currentMembershipTypes = civicrm_api3('MembershipStatus', 'get', array(
      'sequential' => 1,
    ));

    $membershipTypeIds = array();
    $currentMembershipTypeIds = array();
    foreach ($currentMembershipTypes['values'] as $eachCurrentMembershipType) {
      $membershipTypeIds[] = $eachCurrentMembershipType['id'];
      if ($eachCurrentMembershipType['is_current_member']) {
        $currentMembershipTypeIds[] = $eachCurrentMembershipType['id'];
      }
    }

    // 2. Then pass their ids as parameters to the get command.
    $getActiveMembershipParams = array(
      'sequential' => 1,
      'status_id' => $currentMembershipTypeIds,
      'membership_type_id' => array('IN' => $currentMembershipTypeIds),
      'contact_id' => $_SESSION['civicrm_user_connected_orgs']['contact_id'],
      'length' => 0,
    );
    $activeMembershipDetails = civicrm_api3('Membership', 'get', $getActiveMembershipParams);

    $membershipByType = array();

    foreach ($activeMembershipDetails['values'] as $eachMembership) {
      $membershipByType[serialize($eachMembership['name'])] = $eachMembership;
    }

    $_SESSION['civicrm_user_connected_orgs']['active_memberships'] = $membershipByType;

    // Populate active relationships.
    $activeRelationshipDetailsA = civicrm_api3('Relationship', 'get', array(
      'sequential' => 1,
      'contact_id_a' => $_SESSION['civicrm_user_connected_orgs']['contact_id'],
      'is_active' => true,
      'length' => 0,
    ));

    $_SESSION['civicrm_user_connected_orgs']['active_relationships_a'] = $activeRelationshipDetailsA['values'];

    $activeRelationshipDetailsB = civicrm_api3('Relationship', 'get', array(
      'sequential' => 1,
      'contact_id_b' => $_SESSION['civicrm_user_connected_orgs']['contact_id'],
      'is_active' => true,
      'length' => 0,
    ));

    $_SESSION['civicrm_user_connected_orgs']['active_relationships_b'] = $activeRelationshipDetailsB['values'];

  } catch (Exception $ex) {
    drupal_set_message($ex->getMessage(), 'error');
  }
}

function civicrm_user_connected_orgs_token_info() {
  $info = array();

  $info['types']['current_user_civicrm'] = array(
    'name' => t('Current user CiviCRM'),
    'description' => t('Tokens related to the CiviCRM details of the logged in user.'),
  );

  $info['tokens']['current_user_civicrm']['contact_id'] = array(
    'name' => t('Contact ID'),
    'description' => t('The CiviCRM Contact ID of the logged in user.'),
  );

  $info['tokens']['current_user_civicrm']['membership_owner_id'] = array(
    'name' => t('Membership Owner ID'),
    'description' => t('The CiviCRM Contact ID of the parent of the first active membership with a parent id of the logged in user.'),
  );

  $info['tokens']['current_user_civicrm']['employer_id'] = array(
    'name' => t('Contact ID'),
    'description' => t('The CiviCRM Contact ID of the first active employer relationship of the logged in user.'),
  );

  return $info;
}

/**
 * Implements hook_tokens().
 */
function civicrm_user_connected_orgs_tokens($type, $tokens, array $data = array(), array $options = array()) {
  civicrm_initialize();
  
  if ($type != 'current_user_civicrm') {
    return array();
  }

  $replacements = array();

  foreach ($tokens as $name => $original) {
    switch ($name) {
      case 'contact_id':
        $replacements[$original] = $_SESSION['civicrm_user_connected_orgs']['contact_id'];
        break;
      case 'membership_owner_id':
        foreach ($_SESSION['civicrm_user_connected_orgs']['active_memberships'] as $eachMembership) {
          if (array_key_exists('owner_membership_id', $eachMembership)) {
            $ownerMembershipId = civicrm_api3('Membership', 'getvalue', array(
              'sequential' => 1,
              'return' => "contact_id",
              'id' => $eachMembership['owner_membership_id'],
            ));
            watchdog('Connected Orgs', print_r($ownerMembershipId, TRUE), array(), WATCHDOG_ERROR);
            $replacements[$original] = $ownerMembershipId;
            break;
          }
        }
        break;
    }
  }
  return $replacements;
}

function civicrm_user_connected_orgs_views_pre_view(&$view, &$display_id, &$args){
  
  
  $filters = $view->get_items('filter', $display_id);
  foreach ($filters as &$filter) {
    if (!array_key_exists('value', $filter)){
      continue;
    }
    if (!is_array($filter['value'])){
      continue;
    }
    foreach($filter['value'] as $key => $value){
      $filter['value'][$key] = token_replace($value);
    }
    $filter = $view->set_item($display_id, 'filter', $filter['id'], $filter);
  }
}
